import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://login.yahoo.com/")
driver.maximize_window()
time.sleep(3)
driver.find_element(By.XPATH,"//input[@id='login-username']").send_keys("rakesh1595@yahoo.com")
time.sleep(5)
driver.find_element(By.XPATH,"//input[@id='login-signin']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='login-passwd']").send_keys("Gowda@123")
time.sleep(2)
driver.find_element(By.XPATH,"//button[@type='submit']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[text()='Mail']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//a[.='Compose']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//a[.='Compose']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@aria-labelledby='to']").send_keys("rakesh8861@yahoo.com")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@Placeholder='Subject']").send_keys("assigmnet")
time.sleep(2)
driver.find_element(By.XPATH,"//div[@role='textbox']").send_keys("today assingment")
time.sleep(2)
driver.find_element(By.XPATH,"//span[text()='Send']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[.='  Umashankar ']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//span[.='Sign out']").click()
time.sleep(2)
# driver.switch_to.alert.dismiss()
driver.find_element(By.XPATH,"//div[text()='Sign In']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//a[@role='button']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='login-username']").send_keys("rakesh8861")
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='login-signin']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//input[@id='login-passwd']").send_keys("Gowda@123")
time.sleep(2)
driver.find_element(By.XPATH,"//button[@name='verifyPassword']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//div[@title='Mail']").click()
time.sleep(5)
